### PR TITLE
move image to konflux-ci

### PR DESCRIPTION
**Pull request by cuipinghuo**
Related prs:

ReleasePlan pr: https://github.com/redhat-appstudio/tenants-config/pull/495

ReleasePlanAdmission pr: https://github.com/enterprise-contract/golden-container/pull/663/files

### CODE REVIEW

**Comment by zregvart** [comment]
We need the repository created in https://quay.io/organization/konflux-ci and push Secret added to the `rhtap-contract-tenant` namespace and linked to the `appstudio-pipeline` ServiceAccount before this can be merged.

**Comment by lcarva** [comment]
Converting it to a draft for now.

Do we have a tracker for the work that needs to happen before this can proceed?

**Comment by zregvart** [comment]
This is the tracking issue: EC-730

**Comment by cuipinghuo** [comment]
@zregvart @lcarva since the related prs are all mergered on konflux side, is it ok to merge this one to see how it works?

**Comment by zregvart** [comment]
@cuipinghuo go right ahead!

**Comment by zregvart** [comment]
Does the release tag with latest? Then we might want to remove the `.tekton/golden-container-tag-latest.yaml` Pipeline.

**Comment by cuipinghuo** [comment]
> Actually, don't we have a release configured, we then want to push to `quay.io/redhat-user-workloads/rhtap-contract-tenant/golden-container/golden-container:{{revision}}` instead.

the image will be [ec-golden-image](https://quay.io/repository/konflux-ci/ec-golden-image), not sure should be `quay.io/redhat-user-workloads/rhtap-contract-tenant/golden-container/ec-golden-image:{{revision}}` ?

**Comment by zregvart** [comment]
> > Actually, don't we have a release configured, we then want to push to `quay.io/redhat-user-workloads/rhtap-contract-tenant/golden-container/golden-container:{{revision}}` instead.
> 
> the image will be [quay.io/repository/konflux-ci/ec-golden-image](https://quay.io/repository/konflux-ci/ec-golden-image), not sure should be `quay.io/redhat-user-workloads/rhtap-contract-tenant/golden-container/ec-golden-image:{{revision}}` ?

I think that could work, similar to [how ec-cli](https://github.com/enterprise-contract/ec-cli/blob/b203f1cb34d7cc325f71c5df971fd0c3e15636b6/.tekton/cli-main-ci-push.yaml#L25-L26)'s push pipeline pushes

**Comment by cuipinghuo** [comment]
> > > Actually, don't we have a release configured, we then want to push to `quay.io/redhat-user-workloads/rhtap-contract-tenant/golden-container/golden-container:{{revision}}` instead.
> > 
> > 
> > the image will be [quay.io/repository/konflux-ci/ec-golden-image](https://quay.io/repository/konflux-ci/ec-golden-image), not sure should be `quay.io/redhat-user-workloads/rhtap-contract-tenant/golden-container/ec-golden-image:{{revision}}` ?
> 
> I think that could work, similar to [how ec-cli](https://github.com/enterprise-contract/ec-cli/blob/b203f1cb34d7cc325f71c5df971fd0c3e15636b6/.tekton/cli-main-ci-push.yaml#L25-L26)'s push pipeline pushes

checking from log and you are right. Should be

**Comment by zregvart** [comment]
#663 was merged even though it failed in CI, #693 should fix that

**Pull request merged**
